# Part A  (Easy question)

# How many orders were placed in the last month of 2021?

select count(*) from orders
WHERE year(orderdate)=2021 and month(orderdate)=12

# Which products have the highest sales in the 2021 year?

select product,sum(od.quantity) as Total_sales from products as p
join orderdetails as od on p.ProductID=od.ProductID
join orders as o on o.orderid=od.OrderID
where year(orderdate)=2021
group by product 
order by sum(od.quantity) desc

# What is the average order value for customers in a specific country?

select country,round(avg(total_order_amount),0) as average_order_value from customers as c
join orders as o on c.customerid=o.customerid
where country = "India"
group by country 
order by average_order_value desc

#  How many new customers signed up in the last week of 2021?

select count(*) from customers 
where year(DateEntered)=2021 and Week(DateEntered)=52;

#How many new customers signed up in the last week

SELECT COUNT(*) FROM customers 
WHERE DateEntered >= DATE_SUB(NOW(), INTERVAL 1 WEEK);

# What is the total revenue generated by a specific product category?

select categoryName,sum(total_order_amount) as Total_revenue  from orders as o
join orderdetails as od on od.OrderID=o.orderid
join products as p on p.ProductID=od.ProductID
join category as c on c.CategoryID=p.Category_ID
where CategoryName ="Beverages"

# How many orders were placed by a specific customer in the 2020 year?

select count(*) from customers as c
join orders as o on c.customerid=o.customerid
where c.customerid='57085' and year(orderdate)=2020

# Which payment method is used the most by customers?

select PaymentType,count(*) as Total_orders from payments as p
join orders as o on p.paymentid=o.paymentid
group by PaymentType
order by Total_orders desc

# How many orders were shipped to a specific state/province in the last quarter of 2021?

select state,count(*) as Total_orders from customers as c
join orders as o on c.customerid=o.customerid
where quarter(shipdate)=4 and year(shipdate)=2021 and state="Brussels-Capital"
group by state

# What is the total value of discounts given to customers in the july month 2020?

select FirstName,sum(Market_Price-Sale_price) as Discount from customers as c
join orders as o on c.customerid=o.customerid
join orderdetails as  od on od.orderid=o.orderid
join products as p on p.productid=od.productid
where month(orderdate)=6 and year(orderdate)=2021
group by FirstName
order by Discount desc

#part B (Intermediate Question)

# What are the top-selling products by revenue and quantity sold for each month in the 2020 year?

select monthname(orderdate) as month,product,sum(quantity*sale_price) as total_revenue,sum(quantity) as total_quantity from products as p
join orderdetails as od on od.productid=p.productid
join orders as o on od.orderid=o.orderid
where year(orderdate)=2021
group by month,product
order by total_revenue desc ,total_quantity desc

# Which customers have placed the most orders, and what is the average order value for each customer?

select c.customerid,concat(firstname," ",lastname) as Name,count(*) as Total_orders,avg(total_order_amount) as Average_order_amount from customers as c
join orders as o on c.customerid=o.customerid
group by c.customerid,Name
order by Total_orders desc 


# What is the average order value for each category of products, and how has this changed over time?

select DATE_FORMAT(orderdate, '%Y-%m') as order_month,categoryName,avg(total_order_amount) from orders as o
join orderdetails as od on od.OrderID=o.orderid
join products as p on p.ProductID=od.ProductID
join category as c on c.CategoryID=p.Category_ID
group by order_month,categoryname
order by order_month,categoryname
 
# What is the average day it takes to process an order?

select round(avg(DATEDIFF(shipdate,orderdate)),0) as avg_process_day from orders
where shipdate is not null

# Which products have the highest profit margins, and how can we increase profits for lower margin products?

select product,(abs((sale_price-market_price)/sale_price*100)) as profit_margin from products
order by profit_margin desc limit 10
 
#what is the growth in the percentage of first-time buyers from 2020 to 2021

with cte as (
Select customerid ,year(min(orderdate)) as x from orders group by customerid) 
Select ((count(case when x = 2021 then customerid end )- count(case when x = 2020 then customerid end ))
/count(case when x = 2020 then customerid end ))*100 as Presentage_of_first_buyer from cte;

# what is  the number of orders placed for each year in every week.

select weekofyear(orderdate) as Week ,count(case when year(orderdate)=2020 then orderid end ) as Total_orders_in_2020,
count(case when year(orderdate)=2021 then orderid end ) as Total_orders_in_2021 from orders 
group by weekofyear(orderdate) 
order by weekofyear(orderdate)

# create a pivot table based on revenue from different city with year and quarter

with Pivot as ( 
select year(orderdate) as year ,quarter(orderdate) as quarter ,city,sum(total_order_amount) as revenue from orders as o 
join customers as c on c.customerid=o.customerid 
group by year(orderdate),quarter(orderdate),city) 
select year,quarter, 
sum(case when city = "geneva" then revenue end) as geneva, 
sum(case when city = "Brisbane" then revenue end) as Brisbane, 
sum(case when city = "chennai" then revenue end) as chennai, 
sum(case when city = "san francisco" then revenue end) as "san francisco" 
from Pivot group by year,quarter
order by year ,quarter


# part c (Advance queation)

#Print the Productid, Quantity and Orderdate for daily top - 3 selling products between January 2020 to March 2020.
#Essentially you are trying to identify the top 3 products sold for each date between the given date range.
#Sort the result in ascending order of OrderDate, sort them in ascending order of Quantity.

with cte as ( 
select productid,quantity,orderdate,dense_rank() over (partition by orderdate order by quantity desc ) as D 
from orders as o inner join orderdetails as od on o.orderid=od.orderid 
where orderdate between '2020-01-01' and '2020-03-31') 
select productid,quantity,orderdate from cte 
where D between 1 and 3 
order by orderdate,quantity

#what is the total number of order ,total number of uniqe customer and total revenue by each payment method
#if orders are zero put No_orders and customers are zero put No_customers and if revenue are null put No_revenue

with cte as (
select p.paymentid,paymenttype,count(orderid) as orders,
count(distinct c.customerid) as customers, 
ifnull(sum(total_order_amount),"No Payment") as revenue from customers as c 
join orders as o on c.customerid=o.customerid 
right join payments as p on p.paymentid=o.paymentid 
group by p.paymentid,paymenttype) 
select paymentid,paymenttype,
(case when orders =0 then "No orders" else orders end) as Total_orders ,
(case when customers=0 then "No customers" else customers end) Total_customers ,revenue
from cte 
order by paymentid


#Divide the customers in 9 zones depending upon the first letter of the postal codes. and 
#Find the number of order placed by the customers of these zones and the average order amount

select left(postalcode,1) as zone,
count(orderid) as  Orders_placed,avg(total_order_amount) as Avg_order_amount
from customers as c 
join orders as o on c.customerid=o.customerid 
group by left(postalcode,1) 
order by left(postalcode,1)
